IMGUI_KNOBS_DIR = ../../libs/imgui-knobs/example

all:
	$(MAKE) -C  $(IMGUI_KNOBS_DIR)

run: all
	../../libs/imgui-knobs/example/imgui_knobs_example

.PHONY: clean

clean:
	$(MAKE) -C  $(IMGUI_KNOBS_DIR) clean
